<?
$datechar="-";
$script_owner="Egorix";
$owner_email="egorix@yandex.ru";
$owner_icq="339309471";
$owner_website="http://egorix.net.ru";
$passfile="password.dat";
$polldata="data.dat";
$pollcfg="pollcfg.dat";
$cfgfile="conf.php";
?>