.\" (c) 2008 Benoît Tuduri <tuduri.benoit@freesurf.fr>
.\" (c) 2013 Bohdan Stelmakh <chamel@users.sourceforge.net>
.\" 
.\" This document is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This package is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this package; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
.TH "Freesynd" "6" "2013-06-03" "" "ver.0.7.5"
.SH "NAME"
Freesynd \- RTS engine.
.SH "SYNOPSIS"
freesynd [\fB\-h | \-\-help \fR] | [[\fB\-i | \-\-ini <path>\fR] | [ \fB\-\-nosound\fR]]
.SH "DESCRIPTION"
FreeSynd \- a cross-platform,  GPLed reimplementation of engine for the classic Bullfrog game, Syndicate (1993).
.SH "OPTIONS"
These options are available:
.TP
\fB\-h or \-\-help \fR
Give the command line options.
.TP
\fB\-i or \-\-ini <path>\fR
Specify the location of the FreeSynd config file.
.TP
\fB\-\-nosound\fR
Disable all sound.
.SH NOTES
.B In order to run FreeSynd a copy of ORIGINAL Syndicate is required.
.SH "AUTHOR"
This game has been written by :
  Stuart Binge
  Benoit Blancard
  Anders Eurenius
  Tarjei Knapstad
  Davor Ocelic
  Joey Parrish
  Joost Peters
  Bohdan Stelmak
  Bruce Sutherland
  Unavowed
  Trent Waddington
.SH "SEE ALSO"
You can find more about the game on its homepage:

http://freesynd.sourceforge.net/

